@startuml mixin-diamond-1

class Message {
	+Text(): string
}

class EscalatedMessage extends Message {
	+Text(): string
	+Escalated(): string
}

class UnicodeMessage extends Message {
	+Text(): string
	+UnicodeText(): string
}


@enduml

@startuml mixin-diamond-2

class Message {
	+Text(): string
}

interface IEscalatable {
	+Escalated(): string
}

class EscalatedMessage extends Message implements IEscalatable{
	+Text(): string
	+Escalated(): string
}

class UnicodeMessage extends Message {
	+Text(): string
	+UnicodeText(): string
}

class EscalatedUnicodeMessage extends UnicodeMessage implements IEscalatable {
	+Text(): string
	+UnicodeText(): string
	+Escalated(): string
}

@enduml
